input:
 width: 800
 height: 1024
 bboxtype: fbox #bbox(vbox)/hbox/fbox
 batchSize: 4

assign_cfg:
 assignType: default #default/ATSS
 ioutype: iou
 threshold: 0.5

anchors:
 ratios : [3,5]
 scales : [0.75,1]
