device:
 preprocess: cuda1

input:
 height: 800
 width: 1024
 bboxtype: fbox #bbox(vbox)/hbox/fbox
 batchSize: 4

assign_cfg:
 assignType: default #default/ATSS
 ioutype: iou
 threshold: 0.5

anchors:
 ratios : [2,4]
 scales : [0.75,1]

training:
 epoch : 70

inference:
 background_threshold : 0.3
 class_threshold : 0.3
 nms_threshold : 0.7
