device:
 preprocess: cuda1

input:
 width: 32
 height: 32
 bboxtype: fbox #bbox(vbox)/hbox/fbox
 batchSize: 4

assign_cfg:
 assignType: default #default/ATSS
 ioutype: iou
 threshold: 0.5

anchors:
 ratios : [2]
 scales : [0.25]

training:
 epoch : 10

inference:
 background_threshold = 0.5
 class_threshold = 0.5