device:
 preprocess: cuda1

input:
 width: 640
 height: 800
 bboxtype: fbox #bbox(vbox)/hbox/fbox
 batchSize: 3

assign_cfg:
 assignType: default #default/ATSS
 ioutype: iou
 threshold: 0.5

anchors:
 ratios : [3,5]
 scales : [0.75,1]

training:
 epoch : 20

inference:
 background_threshold : 0.5
 class_threshold : 0.5
 nms_threshold : 0.7
